#ifndef BIRD_TILES_H
#define BIRD_TILES_H
/*

 BIRD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 16

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Bank of tiles. */
#define BIRD_SIZE 17
#define BIRD_TILE_SIZE 8
#define BIRD_TILES_BANK 0
#define BIRD_FIRST_ANIMATION_FRAME 1
#define BIRD_LAST_ANIMATION_FRAME 16
#define BIRD_OFFSET 0x00
/* Start of tile array. */
extern unsigned char BirdAnimationTiles[];

/* End of BIRD.H */
#endif /*BIRD_TILES_H*/