/*

 GATE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Bank of tiles. */
#define GATE_SIZE 8
#define GATE_TILE_SIZE 8
#define GATE_TILES_BANK 1
#define GATE_OFFSET 0x20
#define GATE_WIDTH 2
#define GATE_MIN_HEIGHT 1

#define BASE_LEFT 0
#define SHAFT_LEFT 1
#define BASE_LEFT_REVERSE 5
#define BASE_RIGHT_REVERSE 7

#define BASE_RIGHT 2
#define SHAFT_RIGHT 3
#define SHAFT_LEFT_REVERSE 4
#define SHAFT_RIGHT_REVERSE 6

/* Start of tile array. */
extern unsigned char GateTiles[];

/* End of GATE_TILES.H */
