/*

 BG_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : tile_set\bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#define BG_MAP_WIDTH 40
#define BG_MAP_HEIGHT 18
#define BG_MAP_BANK 0
#define MAP_OFFSET 0x30

extern unsigned char bg_map[];

extern void setupMap();

/* End of BG_MAP.H */
